# Generated by Django 3.2.3 on 2021-11-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_leadership_shumilino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propaganda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Propaganda_photo', models.FileField(upload_to='Propaganda/')),
                ('times', models.DateField()),
            ],
        ),
    ]
